### ISSUE TITLE
Fix: Use image.tag in helm chart templates

### ISSUE THREAD

**Issue by mc-eddi** [freiheit-com/kuberpult#1537]
With the introduction of one single appVersion for all services there was a change in consideration of image.tag in the resource helm-release.
We would like to use our rebuilt kuberpult images with different names , e.g. v2.23.1-NG-1 instead of 2.23.1

I would suggest the following change to increase the compatibility of the helm chart templates:

- https://github.com/freiheit-com/kuberpult/blob/main/charts/kuberpult/templates/cd-service.yaml#L78C61-L78C79
Change from:
`image: "{{ .Values.hub }}/{{ .Values.cd.image }}:{{ $.Chart.AppVersion }}"`
to:
`image: "{{ .Values.hub }}/{{ .Values.rollout.image }}:{{ .Values.image.tag | default ($.Chart.AppVersion) }}"`

- https://github.com/freiheit-com/kuberpult/blob/main/charts/kuberpult/templates/frontend-service.yaml#L66C67-L66C85
Change from 
`image: "{{ .Values.hub }}/{{ .Values.frontend.image }}:{{ $.Chart.AppVersion }}"`
to
`image: "{{ .Values.hub }}/{{ .Values.frontend.image }}:{{ .Values.image.tag | default ($.Chart.AppVersion) }}"`

- https://github.com/freiheit-com/kuberpult/blob/main/charts/kuberpult/templates/rollout-service.yaml#L64C66-L64C84
Change from
`image: "{{ .Values.hub }}/{{ .Values.rollout.image }}:{{ $.Chart.AppVersion }}"`
to
`image: "{{ .Values.hub }}/{{ .Values.rollout.image }}:{{ .Values.image.tag | default ($.Chart.AppVersion) }}"`

Best regards
Malte

**Comment by jdvgh** [comment]
You could also just change your Chart.yaml to specify your appVersion accordingly e.g.:

```
apiVersion: v2
appVersion: v2.25.0-2-g55b6ffd
dependencies:
- condition: auth.dexAuth.installDex
  name: dex
  repository: https://charts.dexidp.io
  version: 0.14.2
description: freiheit.com contiuous delivery
maintainers:
- name: hannesg
- name: sven-urbanski-freiheit-com
name: kuberpult
type: application
version: v2.25.0
```
